<?php

namespace Home\ParserBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * FootballRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballRepository extends EntityRepository
{



    public function findCountGames($teamId, $from, $to)
    {
        return $this->createQueryBuilder('f')
            ->select('count(f.id)')
            ->where('f.football_h = ?0')
            ->orwhere( 'f.football_a = ?0')
            ->andwhere('f.date > ?1')
            ->andwhere('f.date < ?2')
            ->setParameters(array($teamId, $from, $to))
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findCountWins($teamId, $from, $to)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE ((f.football_h = :football and f.hts > f.ats) or
                (f.football_a = :football and f.hts < f.ats)) and (f.date > :datefrom and f.date < :dateto)')
        ->setParameter('football', $teamId)
        ->setParameter('datefrom', $from)
        ->setParameter('dateto',$to)
        ;
        $games = $query->getResult();
        $count_wins = count($games);

        return  $count_wins;
    }

    public function findCountDraws($teamId, $from, $to)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE ((f.football_h = :football and f.hts = f.ats) or
                (f.football_a = :football and f.hts = f.ats)) and (f.date > :datefrom and f.date < :dateto)'
        )->setParameter('football', $teamId)
            ->setParameter('datefrom', $from)
            ->setParameter('dateto', $to)
        ;
        $games = $query->getResult();
        $count_draws = count($games);

        return $count_draws;

    }

    public function findCountLosses($teamId, $from, $to)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE ((f.football_h = :football and f.hts < f.ats) or
                (f.football_a = :football and f.hts > f.ats)) and (f.date > :datefrom and f.date < :dateto)')
            ->setParameter('football', $teamId)
            ->setParameter('datefrom', $from)
            ->setParameter('dateto', $to)
        ;
        $games = $query->getResult();
        $count_losses = count($games);

        return $count_losses;
    }

    public function findTeamGames($team)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE (f.football_h = :team) or (f.football_a = :team)')
            ->setParameter('team', 1)
        ;
        $team = $query->getResult();

        return $team;
    }



}
