<?php

namespace Home\ParserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FootballRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootballRepository extends EntityRepository
{
    public function findCountGames($teamId)
    {
        return $this->createQueryBuilder('f')
            ->select('count(f.id)')
            ->where('f.football_h = ?0')
            ->orwhere( 'f.football_a = ?0')
            ->andwhere('f.date > ?1')
            ->andwhere('f.date < ?2')
            ->setParameters(array($teamId, '2011-01-01', '2012-12-01'))
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findCountWins($teamId)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE ((f.football_h = :football and f.hts > f.ats) or
                (f.football_a = :football and f.hts < f.ats)) and (f.date > :datefrom and f.date < :dateto)')
        ->setParameter('football', $teamId)
        ->setParameter('datefrom', '2011-01-01')
        ->setParameter('dateto', '2012-12-12')
        ;
        $games = $query->getResult();
        $count_wins = count($games);

        return  $count_wins;
    }

    public function findCountDraws($teamId)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE ((f.football_h = :football and f.hts = f.ats) or
                (f.football_a = :football and f.hts = f.ats)) and (f.date > :datefrom and f.date < :dateto)'
        )->setParameter('football', $teamId)
            ->setParameter('datefrom', '2011-01-01')
            ->setParameter('dateto', '2012-12-12')
        ;
        $games = $query->getResult();
        $count_draws = count($games);

        return $count_draws;

    }

    public function findCountLosses($teamId)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT f FROM HomeParserBundle:Football f WHERE ((f.football_h = :football and f.hts < f.ats) or
                (f.football_a = :football and f.hts > f.ats)) and (f.date > :datefrom and f.date < :dateto)')
            ->setParameter('football', $teamId)
            ->setParameter('datefrom', '2011-01-01')
            ->setParameter('dateto', '2012-12-12')
        ;
        $games = $query->getResult();
        $count_losses = count($games);

        return $count_losses;
    }



}
