parameters:
#    home_parser.example.class: Home\ParserBundle\Example

services:
#    home_parser.example:
#        class: %home_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
